apiVersion: v1
kind: Pod
metadata:
  name: lembretes
spec:
  containers:
  - name: lembretes
    image: rod19004680/lembretes
    resources:
      limits:
        memory: 256 Mi
        cpu: 1
    
  